/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { ApiKeyOutput, apiKeyOutputSchema } from './apiKeyOutput';

export interface ApiKeyPaginatedOutput {
  cursor?: string;
  hasMore: boolean;
  results: ApiKeyOutput[];
  totalResults: number;
}

export const apiKeyPaginatedOutputSchema: Schema<ApiKeyPaginatedOutput> = object(
  {
    cursor: ['cursor', optional(string())],
    hasMore: ['has_more', boolean()],
    results: ['results', array(lazy(() => apiKeyOutputSchema))],
    totalResults: ['total_results', number()],
  }
);
