/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface ApiKeyCreatedOutput {
  expiration?: string;
  id: string;
  key?: string;
  lastUsed?: string;
  name: string;
  permissions: string[];
}

export const apiKeyCreatedOutputSchema: Schema<ApiKeyCreatedOutput> = object({
  expiration: ['expiration', optional(string())],
  id: ['id', string()],
  key: ['key', optional(string())],
  lastUsed: ['last_used', optional(string())],
  name: ['name', string()],
  permissions: ['permissions', array(string())],
});
