/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, Schema, string } from '../schema';
import { Value, valueSchema } from './value';

export interface Attribute {
  count: number;
  name: string;
  values: Value[];
}

export const attributeSchema: Schema<Attribute> = object({
  count: ['count', number()],
  name: ['name', string()],
  values: ['values', array(lazy(() => valueSchema))],
});
