/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Buyer {
  email?: string;
  /** ChecksumAddress */
  ethAddress?: string;
}

export const buyerSchema: Schema<Buyer> = object({
  email: ['email', optional(string())],
  ethAddress: ['eth_address', optional(string())],
});
