/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import { TypeEnum, typeEnumSchema } from './typeEnum';

export interface CancelItemListingBody {
  id: string;
  type: TypeEnum;
}

export const cancelItemListingBodySchema: Schema<CancelItemListingBody> = object(
  { id: ['id', string()], type: ['type', typeEnumSchema] }
);
