/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CoinbaseCommerceIntegrationInput {
  apiKey: string;
  webhookSecret?: string;
}

export const coinbaseCommerceIntegrationInputSchema: Schema<CoinbaseCommerceIntegrationInput> = object(
  {
    apiKey: ['api_key', string()],
    webhookSecret: ['webhook_secret', optional(string())],
  }
);
