/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface CollectionPath {
  collectionId: string;
}

export const collectionPathSchema: Schema<CollectionPath> = object({
  collectionId: ['collection_id', string()],
});
