/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, Schema, string } from '../schema';
import { Attribute, attributeSchema } from './attribute';

export interface CollectionStats {
  attributes: Attribute[];
  excluded: string[];
  tokensIndexed: number;
}

export const collectionStatsSchema: Schema<CollectionStats> = object({
  attributes: ['attributes', array(lazy(() => attributeSchema))],
  excluded: ['excluded', array(string())],
  tokensIndexed: ['tokens_indexed', number()],
});
