/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  dict,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

export interface Config {
  autoDeploy: boolean;
  /** SafeString */
  autoFundAmount: string;
  /** Uint */
  confirmations: number;
  eip155: boolean;
  gasStrategy?: Record<string, unknown> | null;
  /** Uint */
  maxConcurrentTxs: number;
  poa: boolean;
  /** Uint */
  txResubmitBlockCount?: number;
  /** SafeString */
  url: string;
}

export const configSchema: Schema<Config> = object({
  autoDeploy: ['autoDeploy', boolean()],
  autoFundAmount: ['autoFundAmount', string()],
  confirmations: ['confirmations', number()],
  eip155: ['eip155', boolean()],
  gasStrategy: ['gasStrategy', nullable(dict(unknown()))],
  maxConcurrentTxs: ['maxConcurrentTxs', number()],
  poa: ['poa', boolean()],
  txResubmitBlockCount: ['txResubmitBlockCount', optional(number())],
  url: ['url', string()],
});
