/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ConnectTypeEnum
 */
export enum ConnectTypeEnum {
  STANDARD = 'STANDARD',
  EXPRESS = 'EXPRESS',
  CUSTOM = 'CUSTOM',
}

/**
 * Schema for ConnectTypeEnum
 */
export const connectTypeEnumSchema: Schema<ConnectTypeEnum> = stringEnum(ConnectTypeEnum);
