/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  nullable,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

export interface CreateItemClaimBody {
  /** SafeString */
  email: string;
  variables?: Record<string, unknown> | null;
}

export const createItemClaimBodySchema: Schema<CreateItemClaimBody> = object({
  email: ['email', string()],
  variables: ['variables', optional(nullable(dict(unknown())))],
});
