/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  dict,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { RoyaltyInfo, royaltyInfoSchema } from './royaltyInfo';

export interface CreateProductInput {
  /** SafeString */
  code?: string;
  defaultItemTypeId?: string;
  /** SafeString */
  imageUrl?: string;
  isPublic?: boolean;
  locked?: boolean;
  metaData?: Record<string, unknown> | null;
  /** SafeString */
  name: string;
  royaltyInfo?: RoyaltyInfo;
  tags?: string[];
}

export const createProductInputSchema: Schema<CreateProductInput> = object({
  code: ['code', optional(string())],
  defaultItemTypeId: ['default_item_type_id', optional(string())],
  imageUrl: ['image_url', optional(string())],
  isPublic: ['is_public', optional(boolean())],
  locked: ['locked', optional(boolean())],
  metaData: ['meta_data', optional(nullable(dict(unknown())))],
  name: ['name', string()],
  royaltyInfo: ['royalty_info', optional(lazy(() => royaltyInfoSchema))],
  tags: ['tags', optional(array(string()))],
});
