/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  FundingWalletTypeEnum,
  fundingWalletTypeEnumSchema,
} from './fundingWalletTypeEnum';

export interface CreateOrgWalletInput {
  /** ChecksumAddress */
  address?: string;
  autoFund: boolean;
  custodial: boolean;
  fundingWalletId?: string;
  fundingWalletType?: FundingWalletTypeEnum | null;
  /** SafeString */
  name: string;
  networkIds?: number[];
  restrictNetworks: boolean;
}

export const createOrgWalletInputSchema: Schema<CreateOrgWalletInput> = object({
  address: ['address', optional(string())],
  autoFund: ['auto_fund', boolean()],
  custodial: ['custodial', boolean()],
  fundingWalletId: ['funding_wallet_id', optional(string())],
  fundingWalletType: [
    'funding_wallet_type',
    optional(nullable(fundingWalletTypeEnumSchema)),
  ],
  name: ['name', string()],
  networkIds: ['network_ids', optional(array(number()))],
  restrictNetworks: ['restrict_networks', boolean()],
});
