/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  nullable,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

export interface CreateItemForCollectionBody {
  attributes?: Record<string, unknown> | null;
  itemTypeId?: string;
}

export const createItemForCollectionBodySchema: Schema<CreateItemForCollectionBody> = object(
  {
    attributes: ['attributes', nullable(dict(unknown()))],
    itemTypeId: ['item_type_id', optional(string())],
  }
);
