/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface CreateOrganizationEmailTemplateTestMailPath {
  /** SafeString */
  templateType: string;
}

export const createOrganizationEmailTemplateTestMailPathSchema: Schema<CreateOrganizationEmailTemplateTestMailPath> = object(
  { templateType: ['template_type', string()] }
);
