/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { Meter, meterSchema } from './meter';

export interface CreatePlanInput {
  meters: Meter[];
  /** SafeString */
  name: string;
}

export const createPlanInputSchema: Schema<CreatePlanInput> = object({
  meters: ['meters', array(lazy(() => meterSchema))],
  name: ['name', string()],
});
