/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  nullable,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

export interface CreateItemTypeEndpointBody {
  jsonSchema?: Record<string, unknown> | null;
  /** SafeString */
  name: string;
  organizationId?: string;
}

export const createItemTypeEndpointBodySchema: Schema<CreateItemTypeEndpointBody> = object(
  {
    jsonSchema: ['json_schema', nullable(dict(unknown()))],
    name: ['name', string()],
    organizationId: ['organization_id', optional(string())],
  }
);
