/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CreateUserInput {
  email: string;
  organizationId?: string;
  roleId: string;
}

export const createUserInputSchema: Schema<CreateUserInput> = object({
  email: ['email', string()],
  organizationId: ['organization_id', optional(string())],
  roleId: ['role_id', string()],
});
