/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import {
  OrganizationEmailTemplateVariable,
  organizationEmailTemplateVariableSchema,
} from './organizationEmailTemplateVariable';

export interface CreateOrganizationEmailTemplateTestMailBody {
  /** SafeString */
  html: string;
  /** SafeString */
  subject: string;
  variables: OrganizationEmailTemplateVariable[];
}

export const createOrganizationEmailTemplateTestMailBodySchema: Schema<CreateOrganizationEmailTemplateTestMailBody> = object(
  {
    html: ['html', string()],
    subject: ['subject', string()],
    variables: [
      'variables',
      array(lazy(() => organizationEmailTemplateVariableSchema)),
    ],
  }
);
