/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface CreateWalletPoolBody {
  /** SafeString */
  name: string;
  /** Uint */
  networkId: number;
  /** Uint */
  poolSize: number;
}

export const createWalletPoolBodySchema: Schema<CreateWalletPoolBody> = object({
  name: ['name', string()],
  networkId: ['network_id', number()],
  poolSize: ['pool_size', number()],
});
