/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  nullable,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

export interface CreateOrganizationEmailTemplateBody {
  /** SafeString */
  html: string;
  /** SafeString */
  subject: string;
  unlayerEmbedDesignJson?: Record<string, unknown> | null;
}

export const createOrganizationEmailTemplateBodySchema: Schema<CreateOrganizationEmailTemplateBody> = object(
  {
    html: ['html', string()],
    subject: ['subject', string()],
    unlayerEmbedDesignJson: [
      'unlayer_embed_design_json',
      optional(nullable(dict(unknown()))),
    ],
  }
);
