/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import {
  CreateItemForCollectionBody,
  createItemForCollectionBodySchema,
} from './createItemForCollectionBody';

export interface CreateBulkItemForCollectionBody {
  itemList: CreateItemForCollectionBody[];
}

export const createBulkItemForCollectionBodySchema: Schema<CreateBulkItemForCollectionBody> = object(
  {
    itemList: [
      'item_list',
      array(lazy(() => createItemForCollectionBodySchema)),
    ],
  }
);
