/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface CreateEmailClaimInput {
  email: string;
  itemId: string;
  quantity: number;
}

export const createEmailClaimInputSchema: Schema<CreateEmailClaimInput> = object(
  {
    email: ['email', string()],
    itemId: ['item_id', string()],
    quantity: ['quantity', number()],
  }
);
