/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import {
  TokenAssignmentStrategyEnum,
  tokenAssignmentStrategyEnumSchema,
} from './tokenAssignmentStrategyEnum';

export interface DeployCustomTokenContractBody {
  abi: unknown[];
  /** HexString */
  bytecode: string;
  constructorArgs: unknown[];
  defaultItemTypeId?: string;
  /** Uint */
  networkId: number;
  tokenAssignmentStrategy?: TokenAssignmentStrategyEnum;
  walletpoolId?: string;
}

export const deployCustomTokenContractBodySchema: Schema<DeployCustomTokenContractBody> = object(
  {
    abi: ['abi', array(unknown())],
    bytecode: ['bytecode', string()],
    constructorArgs: ['constructor_args', array(unknown())],
    defaultItemTypeId: ['default_item_type_id', optional(string())],
    networkId: ['network_id', number()],
    tokenAssignmentStrategy: [
      'token_assignment_strategy',
      optional(tokenAssignmentStrategyEnumSchema),
    ],
    walletpoolId: ['walletpool_id', optional(string())],
  }
);
