/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface DeprecatedProductPath {
  productId: string;
}

export const deprecatedProductPathSchema: Schema<DeprecatedProductPath> = object(
  { productId: ['product_id', string()] }
);
