/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { ModeEnum, modeEnumSchema } from './modeEnum';

export interface EditPlatformStripeAccountData {
  config?: Record<string, unknown> | null;
  feePercentageBps?: number;
  mode?: ModeEnum | null;
  name?: string;
  publishableKey?: string;
  secretKey?: string;
  sessionTimeoutMinutes?: number;
  stripeAccountId?: string;
}

export const editPlatformStripeAccountDataSchema: Schema<EditPlatformStripeAccountData> = object(
  {
    config: ['config', optional(nullable(dict(unknown())))],
    feePercentageBps: ['fee_percentage_bps', optional(number())],
    mode: ['mode', optional(nullable(modeEnumSchema))],
    name: ['name', optional(string())],
    publishableKey: ['publishable_key', optional(string())],
    secretKey: ['secret_key', optional(string())],
    sessionTimeoutMinutes: ['session_timeout_minutes', optional(number())],
    stripeAccountId: ['stripe_account_id', optional(string())],
  }
);
