/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface EditWalletPoolBody {
  /** SafeString */
  name: string;
}

export const editWalletPoolBodySchema: Schema<EditWalletPoolBody> = object({
  name: ['name', string()],
});
