/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface EditUserData {
  roleId?: string;
}

export const editUserDataSchema: Schema<EditUserData> = object({
  roleId: ['role_id', optional(string())],
});
