/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, nullable, object, Schema, string, unknown } from '../schema';

export interface EditItemTypeEndpointBody {
  jsonSchema?: Record<string, unknown> | null;
  /** SafeString */
  name: string;
}

export const editItemTypeEndpointBodySchema: Schema<EditItemTypeEndpointBody> = object(
  {
    jsonSchema: ['json_schema', nullable(dict(unknown()))],
    name: ['name', string()],
  }
);
