/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema, string } from '../schema';
import { Config, configSchema } from './config';

export interface EditNetworkData {
  config?: Config;
  enabled?: boolean;
  /** SafeString */
  name?: string;
  testnet?: boolean;
}

export const editNetworkDataSchema: Schema<EditNetworkData> = object({
  config: ['config', optional(lazy(() => configSchema))],
  enabled: ['enabled', optional(boolean())],
  name: ['name', optional(string())],
  testnet: ['testnet', optional(boolean())],
});
