/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { RoyaltyInfo, royaltyInfoSchema } from './royaltyInfo';

export interface EditItemBody {
  attributes?: Record<string, unknown> | null;
  itemTypeId?: string;
  royaltyInfo?: RoyaltyInfo;
}

export const editItemBodySchema: Schema<EditItemBody> = object({
  attributes: ['attributes', optional(nullable(dict(unknown())))],
  itemTypeId: ['item_type_id', optional(string())],
  royaltyInfo: ['royalty_info', optional(lazy(() => royaltyInfoSchema))],
});
