/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface EditPlanPath {
  planId: string;
}

export const editPlanPathSchema: Schema<EditPlanPath> = object({
  planId: ['plan_id', string()],
});
