/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  dict,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import {
  StripeConnectTypeEnum,
  stripeConnectTypeEnumSchema,
} from './stripeConnectTypeEnum';

export interface EditOrganizationData {
  isEnabled?: boolean;
  metaData?: Record<string, unknown> | null;
  mfaRequired?: boolean;
  networkIds?: number[];
  /** SafeString */
  payoutAddress?: string;
  permissions?: string[];
  platformSaleFee?: number;
  stripeConnectTypes?: StripeConnectTypeEnum[];
}

export const editOrganizationDataSchema: Schema<EditOrganizationData> = object({
  isEnabled: ['is_enabled', optional(boolean())],
  metaData: ['meta_data', optional(nullable(dict(unknown())))],
  mfaRequired: ['mfa_required', optional(boolean())],
  networkIds: ['network_ids', optional(array(number()))],
  payoutAddress: ['payout_address', optional(string())],
  permissions: ['permissions', optional(array(string()))],
  platformSaleFee: ['platform_sale_fee', optional(number())],
  stripeConnectTypes: [
    'stripe_connect_types',
    optional(array(stripeConnectTypeEnumSchema)),
  ],
});
