/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  EmailIntegrationOutput,
  emailIntegrationOutputSchema,
} from './emailIntegrationOutput';

export interface EmailIntegrationsPaginatedResult {
  cursor?: string;
  hasMore: boolean;
  results: EmailIntegrationOutput[];
  totalResults: number;
}

export const emailIntegrationsPaginatedResultSchema: Schema<EmailIntegrationsPaginatedResult> = object(
  {
    cursor: ['cursor', optional(string())],
    hasMore: ['has_more', boolean()],
    results: ['results', array(lazy(() => emailIntegrationOutputSchema))],
    totalResults: ['total_results', number()],
  }
);
