/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema, string } from '../schema';

export interface EmailClaim {
  active: boolean;
  claimed: boolean;
  claimedAt?: string;
  collectionId: string;
  createdAt: string;
  email: string;
  expiration: string;
  id: string;
  itemId: string;
  lastPinCodeEmailSentAt?: string;
  quantity: number;
  tokenId: string;
  txHash?: string;
}

export const emailClaimSchema: Schema<EmailClaim> = object({
  active: ['active', boolean()],
  claimed: ['claimed', boolean()],
  claimedAt: ['claimed_at', optional(string())],
  collectionId: ['collection_id', string()],
  createdAt: ['created_at', string()],
  email: ['email', string()],
  expiration: ['expiration', string()],
  id: ['id', string()],
  itemId: ['item_id', string()],
  lastPinCodeEmailSentAt: ['last_pin_code_email_sent_at', optional(string())],
  quantity: ['quantity', number()],
  tokenId: ['token_id', string()],
  txHash: ['tx_hash', optional(string())],
});
