/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { EmailClaim, emailClaimSchema } from './emailClaim';

export interface EmailClaimsPaginatedResult {
  cursor?: string;
  hasMore: boolean;
  results: EmailClaim[];
  totalResults: number;
}

export const emailClaimsPaginatedResultSchema: Schema<EmailClaimsPaginatedResult> = object(
  {
    cursor: ['cursor', optional(string())],
    hasMore: ['has_more', boolean()],
    results: ['results', array(lazy(() => emailClaimSchema))],
    totalResults: ['total_results', number()],
  }
);
