/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface Fees {
  platformSaleFee?: number;
}

export const feesSchema: Schema<Fees> = object({
  platformSaleFee: ['platform_sale_fee', optional(number())],
});
