/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema';

export interface FixedUsage {
  limit: number;
  usage: number;
}

export const fixedUsageSchema: Schema<FixedUsage> = object({
  limit: ['limit', number()],
  usage: ['usage', number()],
});
