/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ForgotPasswordInput {
  /** SafeString */
  email: string;
}

export const forgotPasswordInputSchema: Schema<ForgotPasswordInput> = object({
  email: ['email', string()],
});
