/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface GenerateApiKeyOutput {
  apiKey: string;
}

export const generateApiKeyOutputSchema: Schema<GenerateApiKeyOutput> = object({
  apiKey: ['api_key', string()],
});
