/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema } from '../schema';
import { IncludeEnum, includeEnumSchema } from './includeEnum';

export interface GetAllOrganizationsQuery {
  include?: IncludeEnum[];
}

export const getAllOrganizationsQuerySchema: Schema<GetAllOrganizationsQuery> = object(
  { include: ['include', optional(array(includeEnumSchema))] }
);
