/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, optional, Schema, string } from '../schema';
import {
  OrderDirectionEnum,
  orderDirectionEnumSchema,
} from './orderDirectionEnum';

export interface GetApiKeysInput {
  /** SafeString */
  cursor?: string;
  /** PaginationLimit */
  limit?: number;
  orderDirection?: OrderDirectionEnum | null;
}

export const getApiKeysInputSchema: Schema<GetApiKeysInput> = object({
  cursor: ['cursor', optional(string())],
  limit: ['limit', optional(number())],
  orderDirection: [
    'order_direction',
    optional(nullable(orderDirectionEnumSchema)),
  ],
});
