/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema } from '../schema';
import { Include1Enum, include1EnumSchema } from './include1Enum';

export interface GetCurrentUserQuery {
  include?: Include1Enum[];
}

export const getCurrentUserQuerySchema: Schema<GetCurrentUserQuery> = object({
  include: ['include', optional(array(include1EnumSchema))],
});
