/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, number, object, Schema } from '../schema';
import { PublicItem, publicItemSchema } from './publicItem';

export interface GetClaimOutput {
  isActive: boolean;
  isClaimed: boolean;
  item: PublicItem;
  quantity: number;
}

export const getClaimOutputSchema: Schema<GetClaimOutput> = object({
  isActive: ['is_active', boolean()],
  isClaimed: ['is_claimed', boolean()],
  item: ['item', lazy(() => publicItemSchema)],
  quantity: ['quantity', number()],
});
