/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, optional, Schema, string } from '../schema';
import { OrderBy1Enum, orderBy1EnumSchema } from './orderBy1Enum';
import {
  OrderDirection1Enum,
  orderDirection1EnumSchema,
} from './orderDirection1Enum';
import { Provider1Enum, provider1EnumSchema } from './provider1Enum';

export interface GetEmailIntegrationsQuery {
  /** SafeString */
  cursor?: string;
  /** Uint */
  limit?: number;
  orderBy?: OrderBy1Enum | null;
  orderDirection?: OrderDirection1Enum | null;
  provider?: Provider1Enum | null;
}

export const getEmailIntegrationsQuerySchema: Schema<GetEmailIntegrationsQuery> = object(
  {
    cursor: ['cursor', optional(string())],
    limit: ['limit', optional(number())],
    orderBy: ['order_by', optional(nullable(orderBy1EnumSchema))],
    orderDirection: [
      'order_direction',
      optional(nullable(orderDirection1EnumSchema)),
    ],
    provider: ['provider', optional(nullable(provider1EnumSchema))],
  }
);
