/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface GetItemTypeEndpointPath {
  itemTypeId: string;
}

export const getItemTypeEndpointPathSchema: Schema<GetItemTypeEndpointPath> = object(
  { itemTypeId: ['item_type_id', string()] }
);
