/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface GetPlanSubscriptionPath {
  orgId: string;
}

export const getPlanSubscriptionPathSchema: Schema<GetPlanSubscriptionPath> = object(
  { orgId: ['org_id', string()] }
);
