/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, Schema } from '../schema';

export interface GetPaymentTokensQuery {
  networkId: number[];
}

export const getPaymentTokensQuerySchema: Schema<GetPaymentTokensQuery> = object(
  { networkId: ['network_id', array(number())] }
);
