/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { ListingTypeEnum, listingTypeEnumSchema } from './listingTypeEnum';
import { OrderBy3Enum, orderBy3EnumSchema } from './orderBy3Enum';
import {
  OrderDirection1Enum,
  orderDirection1EnumSchema,
} from './orderDirection1Enum';
import {
  RecipientTypeEnum,
  recipientTypeEnumSchema,
} from './recipientTypeEnum';

export interface GetSalesQuery {
  collectionId: string[];
  /** SafeString */
  cursor?: string;
  itemId: string[];
  /** Uint */
  limit?: number;
  listingType: ListingTypeEnum[];
  orderBy?: OrderBy3Enum | null;
  orderDirection?: OrderDirection1Enum | null;
  recipientType?: RecipientTypeEnum | null;
}

export const getSalesQuerySchema: Schema<GetSalesQuery> = object({
  collectionId: ['collection_id', array(string())],
  cursor: ['cursor', optional(string())],
  itemId: ['item_id', array(string())],
  limit: ['limit', optional(number())],
  listingType: ['listing_type', array(listingTypeEnumSchema)],
  orderBy: ['order_by', optional(nullable(orderBy3EnumSchema))],
  orderDirection: [
    'order_direction',
    optional(nullable(orderDirection1EnumSchema)),
  ],
  recipientType: [
    'recipient_type',
    optional(nullable(recipientTypeEnumSchema)),
  ],
});
