/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface GetSaleByIdPath {
  saleId: string;
}

export const getSaleByIdPathSchema: Schema<GetSaleByIdPath> = object({
  saleId: ['sale_id', string()],
});
