/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { OrderBy4Enum, orderBy4EnumSchema } from './orderBy4Enum';
import {
  OrderDirection1Enum,
  orderDirection1EnumSchema,
} from './orderDirection1Enum';
import { StateEnum, stateEnumSchema } from './stateEnum';
import { TxTypeEnum, txTypeEnumSchema } from './txTypeEnum';

export interface GetTransactionsQuery {
  /** SafeString */
  cursor?: string;
  /** Uint */
  limit?: number;
  networkId: number[];
  orderBy?: OrderBy4Enum | null;
  orderDirection?: OrderDirection1Enum | null;
  signer: string[];
  state: StateEnum[];
  txType: TxTypeEnum[];
}

export const getTransactionsQuerySchema: Schema<GetTransactionsQuery> = object({
  cursor: ['cursor', optional(string())],
  limit: ['limit', optional(number())],
  networkId: ['network_id', array(number())],
  orderBy: ['order_by', optional(nullable(orderBy4EnumSchema))],
  orderDirection: [
    'order_direction',
    optional(nullable(orderDirection1EnumSchema)),
  ],
  signer: ['signer', array(string())],
  state: ['state', array(stateEnumSchema)],
  txType: ['tx_type', array(txTypeEnumSchema)],
});
