/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface GetTransactionByIdPath {
  transactionId: string;
}

export const getTransactionByIdPathSchema: Schema<GetTransactionByIdPath> = object(
  { transactionId: ['transaction_id', string()] }
);
