/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface GetWalletPoolPath {
  id: string;
}

export const getWalletPoolPathSchema: Schema<GetWalletPoolPath> = object({
  id: ['id', string()],
});
