/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for IncludeEnum
 */
export enum IncludeEnum {
  Users = 'users',
}

/**
 * Schema for IncludeEnum
 */
export const includeEnumSchema: Schema<IncludeEnum> = stringEnum(IncludeEnum);
