/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Include1Enum
 */
export enum Include1Enum {
  Organization = 'organization',
}

/**
 * Schema for Include1Enum
 */
export const include1EnumSchema: Schema<Include1Enum> = stringEnum(Include1Enum);
