/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface IntegrationIdPath {
  integrationId: string;
}

export const integrationIdPathSchema: Schema<IntegrationIdPath> = object({
  integrationId: ['integration_id', string()],
});
