/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, nullable, object, Schema, string, unknown } from '../schema';

export interface ItemTypeDomainModel {
  id: string;
  jsonSchema?: Record<string, unknown> | null;
  name: string;
  organizationId: string;
}

export const itemTypeDomainModelSchema: Schema<ItemTypeDomainModel> = object({
  id: ['id', string()],
  jsonSchema: ['json_schema', nullable(dict(unknown()))],
  name: ['name', string()],
  organizationId: ['organization_id', string()],
});
