/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, nullable, object, Schema, unknown } from '../schema';

export interface ItemTypeMetaSchema {
  exampleJsonSchema?: Record<string, unknown> | null;
  metaJsonSchema?: Record<string, unknown> | null;
}

export const itemTypeMetaSchemaSchema: Schema<ItemTypeMetaSchema> = object({
  exampleJsonSchema: ['example_json_schema', nullable(dict(unknown()))],
  metaJsonSchema: ['meta_json_schema', nullable(dict(unknown()))],
});
