/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  ItemTypeDomainModel,
  itemTypeDomainModelSchema,
} from './itemTypeDomainModel';

export interface ItemTypesPaginatedResult {
  cursor?: string;
  hasMore: boolean;
  results: ItemTypeDomainModel[];
  totalResults: number;
}

export const itemTypesPaginatedResultSchema: Schema<ItemTypesPaginatedResult> = object(
  {
    cursor: ['cursor', optional(string())],
    hasMore: ['has_more', boolean()],
    results: ['results', array(lazy(() => itemTypeDomainModelSchema))],
    totalResults: ['total_results', number()],
  }
);
