/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema, string } from '../schema';

export interface ItemClaim {
  claimed: boolean;
  email: string;
  expiration: string;
}

export const itemClaimSchema: Schema<ItemClaim> = object({
  claimed: ['claimed', boolean()],
  email: ['email', string()],
  expiration: ['expiration', string()],
});
