/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { TokenTypeEnum, tokenTypeEnumSchema } from './tokenTypeEnum';

export interface LinkExternalContractBody {
  /** ChecksumAddress */
  address: string;
  /** Uint */
  networkId: number;
  tokenFilter?: Record<string, unknown> | null;
  tokenType: TokenTypeEnum;
}

export const linkExternalContractBodySchema: Schema<LinkExternalContractBody> = object(
  {
    address: ['address', string()],
    networkId: ['network_id', number()],
    tokenFilter: ['token_filter', optional(nullable(dict(unknown())))],
    tokenType: ['token_type', tokenTypeEnumSchema],
  }
);
