/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ListingType3Enum
 */
export enum ListingType3Enum {
  SETPRICE = 'SET_PRICE',
  ONCHAINENGLISHAUCTION = 'ONCHAIN_ENGLISH_AUCTION',
  FIATSETPRICE = 'FIAT_SET_PRICE',
  BUYERMINT = 'BUYER_MINT',
  FIATLAZYMINT = 'FIAT_LAZY_MINT',
  DEFAULT = 'DEFAULT',
}

/**
 * Schema for ListingType3Enum
 */
export const listingType3EnumSchema: Schema<ListingType3Enum> = stringEnum(ListingType3Enum);
