/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, unknown } from '../schema';
import { TypeEnum, typeEnumSchema } from './typeEnum';

export interface Listing {
  data?: unknown;
  type: TypeEnum;
}

export const listingSchema: Schema<Listing> = object({
  data: ['data', unknown()],
  type: ['type', typeEnumSchema],
});
