/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { UserV2Output, userV2OutputSchema } from './userV2Output';

export interface LoginResponse {
  accessToken: string;
  user: UserV2Output;
}

export const loginResponseSchema: Schema<LoginResponse> = object({
  accessToken: ['access_token', string()],
  user: ['user', lazy(() => userV2OutputSchema)],
});
