/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema';
import { TargetEnum, targetEnumSchema } from './targetEnum';
import { Type1Enum, type1EnumSchema } from './type1Enum';

export interface Meter {
  /** Uint */
  limit: number;
  target: TargetEnum;
  type: Type1Enum;
}

export const meterSchema: Schema<Meter> = object({
  limit: ['limit', number()],
  target: ['target', targetEnumSchema],
  type: ['type', type1EnumSchema],
});
