/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Config, configSchema } from './config';
import { PaymentToken, paymentTokenSchema } from './paymentToken';

export interface Network {
  config: Config;
  enabled: boolean;
  /** Uint */
  id: number;
  /** SafeString */
  name: string;
  paymentTokens?: PaymentToken[];
  testnet: boolean;
}

export const networkSchema: Schema<Network> = object({
  config: ['config', lazy(() => configSchema)],
  enabled: ['enabled', boolean()],
  id: ['id', number()],
  name: ['name', string()],
  paymentTokens: [
    'payment_tokens',
    optional(array(lazy(() => paymentTokenSchema))),
  ],
  testnet: ['testnet', boolean()],
});
