/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface NetworkPaymentToken {
  /** ChecksumAddress */
  address: string;
  decimals: number;
  networkId: number;
  symbol: string;
}

export const networkPaymentTokenSchema: Schema<NetworkPaymentToken> = object({
  address: ['address', string()],
  decimals: ['decimals', number()],
  networkId: ['network_id', number()],
  symbol: ['symbol', string()],
});
