/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OnChainStatusEnum
 */
export enum OnChainStatusEnum {
  FAILURE = 'FAILURE',
  SUCCESS = 'SUCCESS',
}

/**
 * Schema for OnChainStatusEnum
 */
export const onChainStatusEnumSchema: Schema<OnChainStatusEnum> = stringEnum(OnChainStatusEnum);
