/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderBy8Enum
 */
export enum OrderBy8Enum {
  UpdatedAt = 'updated_at',
}

/**
 * Schema for OrderBy8Enum
 */
export const orderBy8EnumSchema: Schema<OrderBy8Enum> = stringEnum(OrderBy8Enum);
