/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderBy2Enum
 */
export enum OrderBy2Enum {
  NAME = 'NAME',
}

/**
 * Schema for OrderBy2Enum
 */
export const orderBy2EnumSchema: Schema<OrderBy2Enum> = stringEnum(OrderBy2Enum);
