/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderBy12Enum
 */
export enum OrderBy12Enum {
  CreatedAt = 'created_at',
}

/**
 * Schema for OrderBy12Enum
 */
export const orderBy12EnumSchema: Schema<OrderBy12Enum> = stringEnum(OrderBy12Enum);
