/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderBy3Enum
 */
export enum OrderBy3Enum {
  Timestamp = 'timestamp',
}

/**
 * Schema for OrderBy3Enum
 */
export const orderBy3EnumSchema: Schema<OrderBy3Enum> = stringEnum(OrderBy3Enum);
