/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderDirectionEnum
 */
export enum OrderDirectionEnum {
  ASC = 'ASC',
  DESC = 'DESC',
}

/**
 * Schema for OrderDirectionEnum
 */
export const orderDirectionEnumSchema: Schema<OrderDirectionEnum> = stringEnum(OrderDirectionEnum);
