/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderByEnum
 */
export enum OrderByEnum {
  CreatedAt = 'created_at',
  Expiration = 'expiration',
  ClaimedAt = 'claimed_at',
}

/**
 * Schema for OrderByEnum
 */
export const orderByEnumSchema: Schema<OrderByEnum> = stringEnum(OrderByEnum);
