/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderBy9Enum
 */
export enum OrderBy9Enum {
  NAME = 'NAME',
}

/**
 * Schema for OrderBy9Enum
 */
export const orderBy9EnumSchema: Schema<OrderBy9Enum> = stringEnum(OrderBy9Enum);
