/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderBy6Enum
 */
export enum OrderBy6Enum {
  Age = 'age',
}

/**
 * Schema for OrderBy6Enum
 */
export const orderBy6EnumSchema: Schema<OrderBy6Enum> = stringEnum(OrderBy6Enum);
