/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderDirection1Enum
 */
export enum OrderDirection1Enum {
  Asc = 'asc',
  Desc = 'desc',
}

/**
 * Schema for OrderDirection1Enum
 */
export const orderDirection1EnumSchema: Schema<OrderDirection1Enum> = stringEnum(OrderDirection1Enum);
