/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderDirection8Enum
 */
export enum OrderDirection8Enum {
  ASC = 'ASC',
  DESC = 'DESC',
}

/**
 * Schema for OrderDirection8Enum
 */
export const orderDirection8EnumSchema: Schema<OrderDirection8Enum> = stringEnum(OrderDirection8Enum);
