/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderBy11Enum
 */
export enum OrderBy11Enum {
  Timestamp = 'timestamp',
}

/**
 * Schema for OrderBy11Enum
 */
export const orderBy11EnumSchema: Schema<OrderBy11Enum> = stringEnum(OrderBy11Enum);
