/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderDirection9Enum
 */
export enum OrderDirection9Enum {
  Asc = 'asc',
  Desc = 'desc',
}

/**
 * Schema for OrderDirection9Enum
 */
export const orderDirection9EnumSchema: Schema<OrderDirection9Enum> = stringEnum(OrderDirection9Enum);
