/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';

export interface OrganizationWallet {
  address: string;
  autoFund: boolean;
  custodial: boolean;
  fundingWalletId?: string;
  id: string;
  isDefault: boolean;
  name: string;
  networkIds: number[];
  restrictNetworks: boolean;
}

export const organizationWalletSchema: Schema<OrganizationWallet> = object({
  address: ['address', string()],
  autoFund: ['auto_fund', boolean()],
  custodial: ['custodial', boolean()],
  fundingWalletId: ['funding_wallet_id', optional(string())],
  id: ['id', string()],
  isDefault: ['is_default', boolean()],
  name: ['name', string()],
  networkIds: ['network_ids', array(number())],
  restrictNetworks: ['restrict_networks', boolean()],
});
