/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  dict,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

export interface Organization {
  auth0Id?: string;
  isAdmin: boolean;
  isEnabled: boolean;
  metaData?: Record<string, unknown> | null;
  name: string;
  networkIds?: number[];
}

export const organizationSchema: Schema<Organization> = object({
  auth0Id: ['auth0_id', optional(string())],
  isAdmin: ['is_admin', boolean()],
  isEnabled: ['is_enabled', boolean()],
  metaData: ['meta_data', optional(nullable(dict(unknown())))],
  name: ['name', string()],
  networkIds: ['network_ids', optional(array(number()))],
});
