/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string, unknown } from '../schema';
import { TemplateTypeEnum, templateTypeEnumSchema } from './templateTypeEnum';

export interface OrganizationEmailTemplateVariable {
  /** SafeString */
  defaultValue?: string;
  /** SafeString */
  name: string;
  templateType: TemplateTypeEnum;
  value?: unknown | null;
}

export const organizationEmailTemplateVariableSchema: Schema<OrganizationEmailTemplateVariable> = object(
  {
    defaultValue: ['default_value', optional(string())],
    name: ['name', string()],
    templateType: ['template_type', templateTypeEnumSchema],
    value: ['value', nullable(unknown())],
  }
);
