/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  nullable,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { OriginTypeEnum, originTypeEnumSchema } from './originTypeEnum';
import { TemplateTypeEnum, templateTypeEnumSchema } from './templateTypeEnum';

export interface OrganizationEmailTemplateDomainModel {
  html: string;
  originType: OriginTypeEnum;
  subject: string;
  templateType: TemplateTypeEnum;
  unlayerEmbedDesignJson?: Record<string, unknown> | null;
}

export const organizationEmailTemplateDomainModelSchema: Schema<OrganizationEmailTemplateDomainModel> = object(
  {
    html: ['html', string()],
    originType: ['origin_type', originTypeEnumSchema],
    subject: ['subject', string()],
    templateType: ['template_type', templateTypeEnumSchema],
    unlayerEmbedDesignJson: [
      'unlayer_embed_design_json',
      optional(nullable(dict(unknown()))),
    ],
  }
);
