/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface OrgIdPath {
  orgId: string;
}

export const orgIdPathSchema: Schema<OrgIdPath> = object({
  orgId: ['org_id', string()],
});
