/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OriginTypeEnum
 */
export enum OriginTypeEnum {
  PLATFORMDEFAULT = 'PLATFORM_DEFAULT',
  ORGANIZATIONCUSTOM = 'ORGANIZATION_CUSTOM',
}

/**
 * Schema for OriginTypeEnum
 */
export const originTypeEnumSchema: Schema<OriginTypeEnum> = stringEnum(OriginTypeEnum);
