/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { CoinbaseCommerce, coinbaseCommerceSchema } from './coinbaseCommerce';
import {
  StripeIntegrationOutput,
  stripeIntegrationOutputSchema,
} from './stripeIntegrationOutput';

export interface PaymentIntegrations {
  coinbaseCommerce?: CoinbaseCommerce;
  stripe?: StripeIntegrationOutput;
}

export const paymentIntegrationsSchema: Schema<PaymentIntegrations> = object({
  coinbaseCommerce: [
    'coinbase_commerce',
    optional(lazy(() => coinbaseCommerceSchema)),
  ],
  stripe: ['stripe', optional(lazy(() => stripeIntegrationOutputSchema))],
});
