/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface PaymentsCancelCheckoutInput {
  sessionId: string;
}

export const paymentsCancelCheckoutInputSchema: Schema<PaymentsCancelCheckoutInput> = object(
  { sessionId: ['session_id', string()] }
);
