/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface PaymentToken {
  /** ChecksumAddress */
  address: string;
  /** Uint */
  decimals: number;
  /** SafeString */
  symbol: string;
}

export const paymentTokenSchema: Schema<PaymentToken> = object({
  address: ['address', string()],
  decimals: ['decimals', number()],
  symbol: ['symbol', string()],
});
