/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, nullable, object, Schema, string, unknown } from '../schema';

export interface PaymentIntentOutput {
  data?: Record<string, unknown> | null;
  expiresAt: string;
  id: string;
}

export const paymentIntentOutputSchema: Schema<PaymentIntentOutput> = object({
  data: ['data', nullable(dict(unknown()))],
  expiresAt: ['expires_at', string()],
  id: ['id', string()],
});
