/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { Meter2, meter2Schema } from './meter2';

export interface PlanOutput {
  id: string;
  meters: Meter2[];
  name: string;
}

export const planOutputSchema: Schema<PlanOutput> = object({
  id: ['id', string()],
  meters: ['meters', array(lazy(() => meter2Schema))],
  name: ['name', string()],
});
