/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { ModeEnum, modeEnumSchema } from './modeEnum';

export interface PlatformStripeAccountOutput {
  config?: Record<string, unknown> | null;
  feePercentageBps?: number;
  id: string;
  mode: ModeEnum;
  name: string;
  publishableKey: string;
  sessionTimeoutMinutes: number;
  stripeAccountId: string;
}

export const platformStripeAccountOutputSchema: Schema<PlatformStripeAccountOutput> = object(
  {
    config: ['config', optional(nullable(dict(unknown())))],
    feePercentageBps: ['fee_percentage_bps', optional(number())],
    id: ['id', string()],
    mode: ['mode', modeEnumSchema],
    name: ['name', string()],
    publishableKey: ['publishable_key', string()],
    sessionTimeoutMinutes: ['session_timeout_minutes', number()],
    stripeAccountId: ['stripe_account_id', string()],
  }
);
