/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, number, object, Schema, string } from '../schema';

export interface PlatformWallet {
  address: string;
  custodial: boolean;
  id: string;
  name: string;
  networkIds: number[];
  restrictNetworks: boolean;
}

export const platformWalletSchema: Schema<PlatformWallet> = object({
  address: ['address', string()],
  custodial: ['custodial', boolean()],
  id: ['id', string()],
  name: ['name', string()],
  networkIds: ['network_ids', array(number())],
  restrictNetworks: ['restrict_networks', boolean()],
});
