/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  PlatformStripeAccountOutput,
  platformStripeAccountOutputSchema,
} from './platformStripeAccountOutput';

export interface PlatformStripeAccountPaginatedResults {
  cursor?: string;
  hasMore?: boolean;
  results: PlatformStripeAccountOutput[];
  totalResults: number;
}

export const platformStripeAccountPaginatedResultsSchema: Schema<PlatformStripeAccountPaginatedResults> = object(
  {
    cursor: ['cursor', optional(string())],
    hasMore: ['has_more', optional(boolean())],
    results: ['results', array(lazy(() => platformStripeAccountOutputSchema))],
    totalResults: ['total_results', number()],
  }
);
