/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { ModeEnum, modeEnumSchema } from './modeEnum';

export interface PlatformStripeAccountInput {
  config?: Record<string, unknown> | null;
  feePercentageBps?: number;
  mode: ModeEnum;
  name: string;
  publishableKey: string;
  secretKey: string;
  sessionTimeoutMinutes: number;
  stripeAccountId: string;
}

export const platformStripeAccountInputSchema: Schema<PlatformStripeAccountInput> = object(
  {
    config: ['config', optional(nullable(dict(unknown())))],
    feePercentageBps: ['fee_percentage_bps', optional(number())],
    mode: ['mode', modeEnumSchema],
    name: ['name', string()],
    publishableKey: ['publishable_key', string()],
    secretKey: ['secret_key', string()],
    sessionTimeoutMinutes: ['session_timeout_minutes', number()],
    stripeAccountId: ['stripe_account_id', string()],
  }
);
