/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ProviderEnum
 */
export enum ProviderEnum {
  STRIPE = 'STRIPE',
  COINBASE = 'COINBASE',
}

/**
 * Schema for ProviderEnum
 */
export const providerEnumSchema: Schema<ProviderEnum> = stringEnum(ProviderEnum);
