/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema, string } from '../schema';
import { ModeEnum, modeEnumSchema } from './modeEnum';

export interface PublicPlatformStripeAccountOutput {
  enabled: boolean;
  id: string;
  mode: ModeEnum;
  name: string;
  publishableKey: string;
}

export const publicPlatformStripeAccountOutputSchema: Schema<PublicPlatformStripeAccountOutput> = object(
  {
    enabled: ['enabled', boolean()],
    id: ['id', string()],
    mode: ['mode', modeEnumSchema],
    name: ['name', string()],
    publishableKey: ['publishable_key', string()],
  }
);
