/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, Schema, string } from '../schema';

export interface PublicGetWalletItemsQueryQuery {
  contractAddress: string[];
  networkId: number[];
}

export const publicGetWalletItemsQueryQuerySchema: Schema<PublicGetWalletItemsQueryQuery> = object(
  {
    contractAddress: ['contract_address', array(string())],
    networkId: ['network_id', array(number())],
  }
);
