/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface PublicGetCapabilityPath {
  /** SafeString */
  capability: string;
}

export const publicGetCapabilityPathSchema: Schema<PublicGetCapabilityPath> = object(
  { capability: ['capability', string()] }
);
