/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface PublicNetwork {
  id: number;
  name: string;
}

export const publicNetworkSchema: Schema<PublicNetwork> = object({
  id: ['id', number()],
  name: ['name', string()],
});
