/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { History, historySchema } from './history';

export interface PublicGetItemHistoryViewResponse {
  history: History[];
}

export const publicGetItemHistoryViewResponseSchema: Schema<PublicGetItemHistoryViewResponse> = object(
  { history: ['history', array(lazy(() => historySchema))] }
);
