/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface PublicVerifyClaimPath {
  key: string;
}

export const publicVerifyClaimPathSchema: Schema<PublicVerifyClaimPath> = object(
  { key: ['key', string()] }
);
