/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface PublicOrganizationSchemaV2 {
  auth0Id?: string;
  domain?: string;
  id?: string;
  name?: string;
}

export const publicOrganizationSchemaV2Schema: Schema<PublicOrganizationSchemaV2> = object(
  {
    auth0Id: ['auth0_id', optional(string())],
    domain: ['domain', optional(string())],
    id: ['id', optional(string())],
    name: ['name', optional(string())],
  }
);
