/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface PublicGetItemByContractAndTokenPath {
  /** HexBytes */
  contractAddress: string;
  tokenId: number;
}

export const publicGetItemByContractAndTokenPathSchema: Schema<PublicGetItemByContractAndTokenPath> = object(
  {
    contractAddress: ['contract_address', string()],
    tokenId: ['token_id', number()],
  }
);
