/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { Listing, listingSchema } from './listing';
import { Media, mediaSchema } from './media';
import { TokenContract, tokenContractSchema } from './tokenContract';

export interface PublicItem {
  attributes?: Record<string, unknown> | null;
  collectionId: string;
  id: string;
  listing?: Listing;
  media: Media;
  tokenContract: TokenContract;
  tokenId: string;
}

export const publicItemSchema: Schema<PublicItem> = object({
  attributes: ['attributes', nullable(dict(unknown()))],
  collectionId: ['collection_id', string()],
  id: ['id', string()],
  listing: ['listing', optional(lazy(() => listingSchema))],
  media: ['media', lazy(() => mediaSchema)],
  tokenContract: ['token_contract', lazy(() => tokenContractSchema)],
  tokenId: ['token_id', string()],
});
