/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { PublicItem, publicItemSchema } from './publicItem';

export interface PublicItemsPaginatedResult {
  cursor?: string;
  hasMore: boolean;
  items: PublicItem[];
  totalResults: number;
}

export const publicItemsPaginatedResultSchema: Schema<PublicItemsPaginatedResult> = object(
  {
    cursor: ['cursor', optional(string())],
    hasMore: ['has_more', boolean()],
    items: ['items', array(lazy(() => publicItemSchema))],
    totalResults: ['total_results', number()],
  }
);
