/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string, unknown } from '../schema';

export interface PublicGetCapabilitiesOutput {
  abi: unknown[];
  name: string;
}

export const publicGetCapabilitiesOutputSchema: Schema<PublicGetCapabilitiesOutput> = object(
  { abi: ['abi', array(unknown())], name: ['name', string()] }
);
