/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface PublicItemOwnersOutput {
  /** ChecksumAddress */
  address: string;
  quantity: number;
}

export const publicItemOwnersOutputSchema: Schema<PublicItemOwnersOutput> = object(
  { address: ['address', string()], quantity: ['quantity', number()] }
);
