/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface PublicCollectionOutput {
  id: string;
  name: string;
}

export const publicCollectionOutputSchema: Schema<PublicCollectionOutput> = object(
  { id: ['id', string()], name: ['name', string()] }
);
