/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, Schema } from '../schema';
import { PublicItem, publicItemSchema } from './publicItem';

export interface PublicItemOwnership {
  item: PublicItem;
  quantity: number;
}

export const publicItemOwnershipSchema: Schema<PublicItemOwnership> = object({
  item: ['item', lazy(() => publicItemSchema)],
  quantity: ['quantity', number()],
});
