/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for RecipientTypeEnum
 */
export enum RecipientTypeEnum {
  EMAIL = 'EMAIL',
  ETHADDRESS = 'ETH_ADDRESS',
  OTHER = 'OTHER',
}

/**
 * Schema for RecipientTypeEnum
 */
export const recipientTypeEnumSchema: Schema<RecipientTypeEnum> = stringEnum(RecipientTypeEnum);
