/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for RecipientType3Enum
 */
export enum RecipientType3Enum {
  EMAIL = 'EMAIL',
  ETHADDRESS = 'ETH_ADDRESS',
  OTHER = 'OTHER',
}

/**
 * Schema for RecipientType3Enum
 */
export const recipientType3EnumSchema: Schema<RecipientType3Enum> = stringEnum(RecipientType3Enum);
