/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ResetPasswordUsingTokenInput {
  /** SafeString */
  password: string;
  /** SafeString */
  token: string;
}

export const resetPasswordUsingTokenInputSchema: Schema<ResetPasswordUsingTokenInput> = object(
  { password: ['password', string()], token: ['token', string()] }
);
