/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

export interface RestrictedSignatureRequestInput {
  /** SafeString */
  method: string;
  /** Uint */
  networkId: number;
  parameters?: Record<string, unknown> | null;
  /** ChecksumAddress */
  sender: string;
  /** ChecksumAddress */
  to: string;
  value?: number;
}

export const restrictedSignatureRequestInputSchema: Schema<RestrictedSignatureRequestInput> = object(
  {
    method: ['method', string()],
    networkId: ['network_id', number()],
    parameters: ['parameters', nullable(dict(unknown()))],
    sender: ['sender', string()],
    to: ['to', string()],
    value: ['value', optional(number())],
  }
);
