/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface RoleSchemaV2 {
  id?: string;
  name?: string;
}

export const roleSchemaV2Schema: Schema<RoleSchemaV2> = object({
  id: ['id', optional(string())],
  name: ['name', optional(string())],
});
