/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface RoyaltyInfo {
  /** BasisPoints */
  amountBps: number;
  /** ChecksumAddress */
  receiver: string;
}

export const royaltyInfoSchema: Schema<RoyaltyInfo> = object({
  amountBps: ['amount_bps', number()],
  receiver: ['receiver', string()],
});
