/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  nullable,
  number,
  object,
  Schema,
  string,
  unknown,
} from '../schema';
import { ListingTypeEnum, listingTypeEnumSchema } from './listingTypeEnum';
import {
  RecipientTypeEnum,
  recipientTypeEnumSchema,
} from './recipientTypeEnum';

export interface SaleOutput {
  currency: string;
  id: string;
  itemId: string;
  listingType: ListingTypeEnum;
  providerDetails?: Record<string, unknown> | null;
  quantity: number;
  recipient: string;
  recipientType: RecipientTypeEnum;
  saleAmount: string;
  timestamp: string;
  txHash: string;
}

export const saleOutputSchema: Schema<SaleOutput> = object({
  currency: ['currency', string()],
  id: ['id', string()],
  itemId: ['item_id', string()],
  listingType: ['listing_type', listingTypeEnumSchema],
  providerDetails: ['provider_details', nullable(dict(unknown()))],
  quantity: ['quantity', number()],
  recipient: ['recipient', string()],
  recipientType: ['recipient_type', recipientTypeEnumSchema],
  saleAmount: ['sale_amount', string()],
  timestamp: ['timestamp', string()],
  txHash: ['tx_hash', string()],
});
