/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  nullable,
  number,
  object,
  optional,
  Schema,
  unknown,
} from '../schema';
import { TypeEnum, typeEnumSchema } from './typeEnum';

export interface SellItemBody {
  data?: Record<string, unknown> | null;
  /** Uint */
  quantity?: number;
  type: TypeEnum;
}

export const sellItemBodySchema: Schema<SellItemBody> = object({
  data: ['data', nullable(dict(unknown()))],
  quantity: ['quantity', optional(number())],
  type: ['type', typeEnumSchema],
});
