/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface SendTestEmailInput {
  /** SafeString */
  to: string;
}

export const sendTestEmailInputSchema: Schema<SendTestEmailInput> = object({
  to: ['to', string()],
});
