/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface SetPlanSubscriptionOutput {
  organizationId: string;
  planId: string;
  startDate: string;
}

export const setPlanSubscriptionOutputSchema: Schema<SetPlanSubscriptionOutput> = object(
  {
    organizationId: ['organization_id', string()],
    planId: ['plan_id', string()],
    startDate: ['start_date', string()],
  }
);
