/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface SetPlanSubscriptionData {
  planId: string;
  startDate: string;
}

export const setPlanSubscriptionDataSchema: Schema<SetPlanSubscriptionData> = object(
  { planId: ['plan_id', string()], startDate: ['start_date', string()] }
);
