/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface SetPlanSubscriptionPath {
  orgId: string;
}

export const setPlanSubscriptionPathSchema: Schema<SetPlanSubscriptionPath> = object(
  { orgId: ['org_id', string()] }
);
