/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface StatusResponse {
  status: string;
}

export const statusResponseSchema: Schema<StatusResponse> = object({
  status: ['status', string()],
});
