/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for StripeConnectTypeEnum
 */
export enum StripeConnectTypeEnum {
  STANDARD = 'STANDARD',
  EXPRESS = 'EXPRESS',
  CUSTOM = 'CUSTOM',
}

/**
 * Schema for StripeConnectTypeEnum
 */
export const stripeConnectTypeEnumSchema: Schema<StripeConnectTypeEnum> = stringEnum(StripeConnectTypeEnum);
