/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import { ConnectTypeEnum, connectTypeEnumSchema } from './connectTypeEnum';

export interface StripePaymentsSetupInput {
  connectType: ConnectTypeEnum;
  platformStripeAccountId: string;
}

export const stripePaymentsSetupInputSchema: Schema<StripePaymentsSetupInput> = object(
  {
    connectType: ['connect_type', connectTypeEnumSchema],
    platformStripeAccountId: ['platform_stripe_account_id', string()],
  }
);
