/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface StripePaymentsSetupOutput {
  url: string;
}

export const stripePaymentsSetupOutputSchema: Schema<StripePaymentsSetupOutput> = object(
  { url: ['url', string()] }
);
