/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, Schema, string } from '../schema';
import { ConnectTypeEnum, connectTypeEnumSchema } from './connectTypeEnum';
import {
  PublicPlatformStripeAccountOutput,
  publicPlatformStripeAccountOutputSchema,
} from './publicPlatformStripeAccountOutput';

export interface StripeIntegrationOutput {
  accountId: string;
  connectType: ConnectTypeEnum;
  platformStripeAccount: PublicPlatformStripeAccountOutput;
  setupComplete: boolean;
}

export const stripeIntegrationOutputSchema: Schema<StripeIntegrationOutput> = object(
  {
    accountId: ['account_id', string()],
    connectType: ['connect_type', connectTypeEnumSchema],
    platformStripeAccount: [
      'platform_stripe_account',
      lazy(() => publicPlatformStripeAccountOutputSchema),
    ],
    setupComplete: ['setup_complete', boolean()],
  }
);
