/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TargetEnum
 */
export enum TargetEnum {
  MINTTOKEN = 'MINT_TOKEN',
  TOKENCONTRACT = 'TOKEN_CONTRACT',
  USERCOUNT = 'USER_COUNT',
  PRODUCTCOUNT = 'PRODUCT_COUNT',
}

/**
 * Schema for TargetEnum
 */
export const targetEnumSchema: Schema<TargetEnum> = stringEnum(TargetEnum);
