/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema } from '../schema';

export interface TestWebhookOutput {
  response?: number;
  success: boolean;
}

export const testWebhookOutputSchema: Schema<TestWebhookOutput> = object({
  response: ['response', optional(number())],
  success: ['success', boolean()],
});
