/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface TestWebhookInput {
  /** SafeString */
  secret: string;
  /** SafeString */
  url: string;
}

export const testWebhookInputSchema: Schema<TestWebhookInput> = object({
  secret: ['secret', string()],
  url: ['url', string()],
});
