/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TokenTypeEnum
 */
export enum TokenTypeEnum {
  ERC721 = 'ERC721',
  ERC1155 = 'ERC1155',
}

/**
 * Schema for TokenTypeEnum
 */
export const tokenTypeEnumSchema: Schema<TokenTypeEnum> = stringEnum(TokenTypeEnum);
