/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TokenStatusEnum
 */
export enum TokenStatusEnum {
  TOKENIZED = 'TOKENIZED',
  NOTTOKENIZED = 'NOT_TOKENIZED',
  TOKENIZING = 'TOKENIZING',
  PROVISIONED = 'PROVISIONED',
  PROVISIONING = 'PROVISIONING',
}

/**
 * Schema for TokenStatusEnum
 */
export const tokenStatusEnumSchema: Schema<TokenStatusEnum> = stringEnum(TokenStatusEnum);
