/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';
import { CapabilityEnum, capabilityEnumSchema } from './capabilityEnum';
import { TokenTypeEnum, tokenTypeEnumSchema } from './tokenTypeEnum';

export interface TokenContract {
  /** ChecksumAddress */
  address?: string;
  capabilities: CapabilityEnum[];
  deployTxId?: string;
  networkId: number;
  symbol: string;
  tokenType: TokenTypeEnum;
  txHash?: string;
}

export const tokenContractSchema: Schema<TokenContract> = object({
  address: ['address', optional(string())],
  capabilities: ['capabilities', array(capabilityEnumSchema)],
  deployTxId: ['deploy_tx_id', optional(string())],
  networkId: ['network_id', number()],
  symbol: ['symbol', string()],
  tokenType: ['token_type', tokenTypeEnumSchema],
  txHash: ['tx_hash', optional(string())],
});
