/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TokenAssignmentStrategyEnum
 */
export enum TokenAssignmentStrategyEnum {
  RANDOMAFTERMINT = 'RANDOM_AFTER_MINT',
  INCREMENTALATPROVISION = 'INCREMENTAL_AT_PROVISION',
}

/**
 * Schema for TokenAssignmentStrategyEnum
 */
export const tokenAssignmentStrategyEnumSchema: Schema<TokenAssignmentStrategyEnum> = stringEnum(TokenAssignmentStrategyEnum);
