/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface TransferItemBody {
  /** Uint */
  quantity?: number;
  /** ChecksumAddress */
  to: string;
}

export const transferItemBodySchema: Schema<TransferItemBody> = object({
  quantity: ['quantity', optional(number())],
  to: ['to', string()],
});
