/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  TransactionOutput,
  transactionOutputSchema,
} from './transactionOutput';

export interface TransactionsPaginatedResult {
  cursor?: string;
  hasMore: boolean;
  results: TransactionOutput[];
  totalResults: number;
}

export const transactionsPaginatedResultSchema: Schema<TransactionsPaginatedResult> = object(
  {
    cursor: ['cursor', optional(string())],
    hasMore: ['has_more', boolean()],
    results: ['results', array(lazy(() => transactionOutputSchema))],
    totalResults: ['total_results', number()],
  }
);
