/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface UpdateOrganizationPlatformStripeAccountPath {
  orgId: string;
  platformStripeAccountId: string;
}

export const updateOrganizationPlatformStripeAccountPathSchema: Schema<UpdateOrganizationPlatformStripeAccountPath> = object(
  {
    orgId: ['org_id', string()],
    platformStripeAccountId: ['platform_stripe_account_id', string()],
  }
);
