/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface UserPath {
  userId: string;
}

export const userPathSchema: Schema<UserPath> = object({
  userId: ['user_id', string()],
});
