/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface Value {
  count: number;
  name: string;
}

export const valueSchema: Schema<Value> = object({
  count: ['count', number()],
  name: ['name', string()],
});
