/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface VerifyWeb2Input {
  /** SafeString */
  email: string;
  /** SafeString */
  password: string;
  /** SafeString */
  token: string;
}

export const verifyWeb2InputSchema: Schema<VerifyWeb2Input> = object({
  email: ['email', string()],
  password: ['password', string()],
  token: ['token', string()],
});
