/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface Wallets {
  autoFund?: boolean;
  opsAddress?: string;
  payoutAddress?: string;
}

export const walletsSchema: Schema<Wallets> = object({
  autoFund: ['auto_fund', optional(boolean())],
  opsAddress: ['ops_address', optional(string())],
  payoutAddress: ['payout_address', optional(string())],
});
