/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Web2LoginInput {
  /** SafeString */
  email: string;
  /** SafeString */
  password: string;
}

export const web2LoginInputSchema: Schema<Web2LoginInput> = object({
  email: ['email', string()],
  password: ['password', string()],
});
