/**
 * Treum Platform APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema, string } from '../schema';

export interface Webhook {
  enabled: boolean;
  id: string;
  /** SafeString */
  name: string;
  /** SafeString */
  secret: string;
  /** SafeString */
  url: string;
}

export const webhookSchema: Schema<Webhook> = object({
  enabled: ['enabled', boolean()],
  id: ['id', string()],
  name: ['name', string()],
  secret: ['secret', string()],
  url: ['url', string()],
});
